export const ACTION_TYPE = {
	LOGOUT: 'LOGOUT',
	SET_USER: 'SET_USER',

	ADD_PRODUCT_IN_CART: 'ADD_PRODUCT_IN_CART',
	REMOVE_PRODUCT_FROM_CART: 'REMOVE_PRODUCT_FROM_CART',
	RESET_PRODUCT_DATA: 'RESET_PRODUCT_DATA',
	RESET_PRODUCTS_DATA: 'RESET_PRODUCTS_DATA',
	SET_PRODUCT_DATA: 'SET_PRODUCT_DATA',
	SET_PRODUCTS_DATA: 'SET_PRODUCTS_DATA',
	SET_PRODUCT_CATEGORIES_DATA: 'SET_PRODUCT_DATA',
	SET_SHOPPING_CART_DATA: 'SET_SHOPPING_CART_DATA',

	CLOSE_MODAL: 'CLOSE_MODAL',
	OPEN_MODAL: 'OPEN_MODAL',
};
